[versions]
guava = "33.5.0-jre"
ipaddress = "5.5.1"
kotest = "6.0.4"
kotlin = "2.2.21"
kotlinx-coroutines = "1.10.2"
kotlinx-serialization = "1.9.0"
mockk = "1.13.14"
node-gradle = "7.1.0"
# @keep
nodejs = "24.11.0"
# @keep
npm = "11.6.2"
spotless = "8.0.0"
spring-boot = "3.5.7"
spring-dependency-management = "1.1.7"
springmockk = "4.0.2"
version-catalog-update = "1.0.1"
versions = "0.53.0"

[libraries]
flyway-core = { module = "org.flywaydb:flyway-core" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
h2 = { module = "com.h2database:h2" }
ipaddress = { module = "com.github.seancfoley:ipaddress", version.ref = "ipaddress" }
kotest-bom = { module = "io.kotest:kotest-bom", version.ref = "kotest" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core" }
kotest-assertions-json = { module = "io.kotest:kotest-assertions-json" }
kotest-assertions-shared = { module = "io.kotest:kotest-assertions-shared" }
kotest-extensions-spring = { module = "io.kotest:kotest-extensions-spring" }
kotest-property = { module = "io.kotest:kotest-property" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlinx-coroutines-bom = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-bom", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core" }
kotlinx-coroutines-debug = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-debug" }
kotlinx-coroutines-reactive = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactive" }
kotlinx-coroutines-reactor = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactor" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test" }
kotlinx-serialization-bom = { module = "org.jetbrains.kotlinx:kotlinx-serialization-bom", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
r2dbc-h2 = { module = "io.r2dbc:r2dbc-h2" }
reactor-kotlin-extensions = { module = "io.projectreactor.kotlin:reactor-kotlin-extensions" }
reactor-test = { module = "io.projectreactor:reactor-test" }
spring-boot-configuration-processor = { module = "org.springframework.boot:spring-boot-configuration-processor" }
spring-boot-devtools = { module = "org.springframework.boot:spring-boot-devtools" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-starter-data-r2dbc = { module = "org.springframework.boot:spring-boot-starter-data-r2dbc" }
spring-boot-starter-jdbc = { module = "org.springframework.boot:spring-boot-starter-jdbc" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-starter-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux" }
springmockk = { module = "com.ninja-squad:springmockk", version.ref = "springmockk" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
node-gradle = { id = "com.github.node-gradle.node", version.ref = "node-gradle" }
project-report = { id = "project-report" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "version-catalog-update" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }
